We are create Python scripts to gather real-time Mutual Fund information from the Association of Mutual Funds (AMFI).

*In Python, a "MODULE" is like a special toolbox filled with different tools (FUNTIONS) that can help you do specific tasks without needing to build everything from scratch.*

The mftool module is one of these toolboxes, and it’s designed specifically to get information about Mutual Funds in India. Mutual Funds are a way for people to invest their money, so it can grow over time. mftool helps by giving us real-time information about these investments.

With mftool, we can:

- Look up the current value of different mutual funds
- See a list of all available mutual fund options
- Check the history of a fund’s value over time

In [34]:
##### Run this module into your terminal
!pip install mftool

Requirement already satisfied: mftool in /usr/local/lib/python3.10/dist-packages (2.8)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from mftool) (2.32.3)
Requirement already satisfied: bs4 in /usr/local/lib/python3.10/dist-packages (from mftool) (0.0.2)
Requirement already satisfied: httpx in /usr/local/lib/python3.10/dist-packages (from mftool) (0.27.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from mftool) (2.2.2)
Requirement already satisfied: yfinance in /usr/local/lib/python3.10/dist-packages (from mftool) (0.2.48)
Requirement already satisfied: Deprecated in /usr/local/lib/python3.10/dist-packages (from mftool) (1.2.14)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from bs4->mftool) (4.12.3)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.10/dist-packages (from Deprecated->mftool) (1.16.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx->mftool) (3.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx->mftool) (2024.8.30)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx->mftool) (1.0.6)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx->mftool) (3.10)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx->mftool) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx->mftool) (0.14.0)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas->mftool) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->mftool) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->mftool) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->mftool) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->mftool) (3.4.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->mftool) (2.2.3)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.10/dist-packages (from yfinance->mftool) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.10/dist-packages (from yfinance->mftool) (5.3.0)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from yfinance->mftool) (4.3.6)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.10/dist-packages (from yfinance->mftool) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.10/dist-packages (from yfinance->mftool) (3.17.7)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.10/dist-packages (from yfinance->mftool) (1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->bs4->mftool) (2.6)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance->mftool) (1.16.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance->mftool) (0.5.1)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio->httpx->mftool) (1.2.2)

In [35]:
##### Import module and create an object for Mftool
from mftool import Mftool

obj = Mftool()

In [36]:
##### Import Libraries
import pandas as pd                                                             # helps working with data, especially in tables (like rows and columns in a spreadsheet)
                                                                                # widely used for data analysis and manipulation
import matplotlib.pyplot as plt                                                 # used for data visualization

import pprint                                                                   # pretty print helps display information in a way that’s easy to read

In [37]:
##### List of Mutual Funds Scheme Codes & Names with get_scheme_codes() method
##### Scheme codes are like unique IDs for each mutual fund, so we can keep track of them
data = obj.get_scheme_codes()

print(len(data))
print(type(data))

# pprint.pprint(data)

13580
<class 'dict'>

In [38]:
##### Display the data as a DataFrame (a table-like structure) instead of a dictionary
##### Which makes it easier to view if you have a large amount of data
df = pd.DataFrame.from_dict(data, orient='index', columns=['Value']).reset_index()
df.columns = ['Scheme Code', 'Scheme Name']
df = df.drop(index=0).reset_index(drop=True)

print(len(df))

13579

In [39]:
df.head()

  Scheme Code                                        Scheme Name
0      119551  Aditya Birla Sun Life Banking & PSU Debt Fund ...
1      119552  Aditya Birla Sun Life Banking & PSU Debt Fund ...
2      119553  Aditya Birla Sun Life Banking & PSU Debt Fund ...
3      108272  Aditya Birla Sun Life Banking & PSU Debt Fund ...
4      110282  Aditya Birla Sun Life Banking & PSU Debt Fund ...

##### Display the scheme code for a specific scheme name in the DataFrame

In [40]:
initials = input("Please suggest the initials of the scheme name: ")            # prompt for input the scheme name

matching_schemes = df[df["Scheme Name"].str.contains(initials, case=False)]     # filter the DataFrame for names that contain the initials

print(matching_schemes)                                                         # display the matching scheme codes and names

Please suggest the initials of the scheme name: Nippon India growth
     Scheme Code                                        Scheme Name
4189      118666  NIPPON INDIA GROWTH FUND - DIRECT Plan - IDCW ...
4190      118665  Nippon India Growth Fund - Direct Plan Growth ...
4191      118668  Nippon India Growth Fund - Direct Plan Growth ...
4192      100375             NIPPON INDIA GROWTH FUND - IDCW Option
4193      106260  NIPPON INDIA GROWTH FUND - INSTITUTIONAL Plan ...
4194      100376  Nippon India Growth Fund-Growth Plan-Bonus Option
4195      100377  Nippon India Growth Fund-Growth Plan-Growth Op...

In [64]:
##### Getting a Scheme Quote with get_scheme_quote() methods
Scheme_Code = input("Please enter the scheme code: ")
data1 = obj.get_scheme_quote(Scheme_Code)

if data1:
   pprint.pprint(data1)
else:
   print("No data found for the provided scheme code.")

Please enter the scheme code: 118668
{'last_updated': '04-Nov-2024',
 'nav': '4371.5134',
 'scheme_code': '118668',
 'scheme_name': 'Nippon India Growth Fund - Direct Plan Growth Plan - Growth '
                'Option'}

In [65]:
##### Display the data as a DataFrame (a table-like structure)
df1 = pd.DataFrame.from_dict(data1, orient='index').reset_index()               # Convert the Dictionary to a DataFrame

df1.columns = ['Key', 'Value']                                                  # Rename the columns for clarity

df1.head(10)

            Key                                              Value
0   scheme_code                                             118668
1   scheme_name  Nippon India Growth Fund - Direct Plan Growth ...
2  last_updated                                        04-Nov-2024
3           nav                                          4371.5134

In [66]:
##### Get Scheme details with specific Scheme code using get_scheme_details() methods
data2 = obj.get_scheme_details(Scheme_Code)

pprint.pprint(data2)

{'fund_house': 'Nippon India Mutual Fund',
 'scheme_category': 'Equity Scheme - Mid Cap Fund',
 'scheme_code': 118668,
 'scheme_name': 'Nippon India Growth Fund - Direct Plan Growth Plan - Growth '
                'Option',
 'scheme_start_date': {'date': '02-01-2013', 'nav': '507.16170'},
 'scheme_type': 'Open Ended Schemes'}

In [67]:
##### Get Scheme Historical NAV’s data using get_scheme_historical_nav() methods
data3 = obj.get_scheme_historical_nav(Scheme_Code)

pprint.pprint(data3)

{'data': [{'date': '04-11-2024', 'nav': '4371.51340'},
          {'date': '31-10-2024', 'nav': '4388.91090'},
          {'date': '30-10-2024', 'nav': '4389.50920'},
          {'date': '29-10-2024', 'nav': '4393.86540'},
          {'date': '28-10-2024', 'nav': '4354.28520'},
          {'date': '25-10-2024', 'nav': '4348.59480'},
          {'date': '24-10-2024', 'nav': '4418.83590'},
          {'date': '23-10-2024', 'nav': '4427.02100'},
          {'date': '22-10-2024', 'nav': '4400.34880'},
          {'date': '21-10-2024', 'nav': '4506.20830'},
          {'date': '18-10-2024', 'nav': '4560.71560'},
          {'date': '17-10-2024', 'nav': '4547.99260'},
          {'date': '16-10-2024', 'nav': '4623.09160'},
          {'date': '15-10-2024', 'nav': '4640.00910'},
          {'date': '14-10-2024', 'nav': '4606.65380'},
          {'date': '11-10-2024', 'nav': '4580.20640'},
          {'date': '10-10-2024', 'nav': '4558.90460'},
          {'date': '09-10-2024', 'nav': '4568.32550'},
          {'date': '08-10-2024', 'nav': '4525.08250'},
          {'date': '07-10-2024', 'nav': '4418.65350'},
          {'date': '04-10-2024', 'nav': '4506.32320'},
          {'date': '03-10-2024', 'nav': '4552.54590'},
          {'date': '01-10-2024', 'nav': '4644.06770'},
          {'date': '30-09-2024', 'nav': '4623.46350'},
          {'date': '27-09-2024', 'nav': '4631.23490'},
          {'date': '26-09-2024', 'nav': '4630.77850'},
          {'date': '25-09-2024', 'nav': '4628.96040'},
          {'date': '24-09-2024', 'nav': '4657.79560'},
          {'date': '23-09-2024', 'nav': '4650.82960'},
          {'date': '20-09-2024', 'nav': '4615.05440'},
          {'date': '19-09-2024', 'nav': '4566.24460'},
          {'date': '18-09-2024', 'nav': '4578.87140'},
          {'date': '17-09-2024', 'nav': '4582.34230'},
          {'date': '16-09-2024', 'nav': '4577.46040'},
          {'date': '13-09-2024', 'nav': '4555.26950'},
          {'date': '12-09-2024', 'nav': '4536.94630'},
          {'date': '11-09-2024', 'nav': '4479.45280'},
          {'date': '10-09-2024', 'nav': '4493.71850'},
          {'date': '09-09-2024', 'nav': '4456.30520'},
          {'date': '06-09-2024', 'nav': '4465.39990'},
          {'date': '05-09-2024', 'nav': '4518.88340'},
          {'date': '04-09-2024', 'nav': '4492.07680'},
          {'date': '03-09-2024', 'nav': '4488.19920'},
          {'date': '02-09-2024', 'nav': '4472.15860'},
          {'date': '30-08-2024', 'nav': '4473.32620'},
          {'date': '29-08-2024', 'nav': '4443.17260'},
          {'date': '28-08-2024', 'nav': '4451.67240'},
          {'date': '27-08-2024', 'nav': '4453.69350'},
          {'date': '26-08-2024', 'nav': '4445.85460'},
          {'date': '23-08-2024', 'nav': '4430.00560'},
          {'date': '22-08-2024', 'nav': '4434.25050'},
          {'date': '21-08-2024', 'nav': '4410.03530'},
          {'date': '20-08-2024', 'nav': '4386.68620'},
          {'date': '19-08-2024', 'nav': '4338.82740'},
          {'date': '16-08-2024', 'nav': '4326.27030'},
          {'date': '14-08-2024', 'nav': '4264.30660'},
          {'date': '13-08-2024', 'nav': '4271.24840'},
          {'date': '12-08-2024', 'nav': '4306.18500'},
          {'date': '09-08-2024', 'nav': '4316.99470'},
          {'date': '08-08-2024', 'nav': '4274.97600'},
          {'date': '07-08-2024', 'nav': '4283.69820'},
          {'date': '06-08-2024', 'nav': '4204.62900'},
          {'date': '05-08-2024', 'nav': '4234.42660'},
          {'date': '02-08-2024', 'nav': '4378.40740'},
          {'date': '01-08-2024', 'nav': '4413.59120'},
          {'date': '31-07-2024', 'nav': '4440.73230'},
          {'date': '30-07-2024', 'nav': '4411.27660'},
          {'date': '29-07-2024', 'nav': '4406.65850'},
          {'date': '26-07-2024', 'nav': '4374.97030'},
          {'date': '25-07-2024', 'nav': '4302.04290'},
          {'date': '24-07-2024', 'nav': '4304.70820'},
          {'date': '23-07-2024', 'nav': '4259.28010'},
          {'date': '22-07-2024', 'nav': '4276.98890'},
          {'date': '19-07-2024', 'nav': '4233.06390'},
          {'date': '18-07-2024', 'nav': '4317.00260'},
          {'date': '16-07-2024', 'nav': '4349.93530'},
          {'date': '15-07-2024', 'nav': '4354.92130'},
          {'date': '12-07-2024', 'nav': '4322.60620'},
          {'date': '11-07-2024', 'nav': '4327.78280'},
          {'date': '10-07-2024', 'nav': '4314.30260'},
          {'date': '09-07-2024', 'nav': '4314.94020'},
          {'date': '08-07-2024', 'nav': '4291.45810'},
          {'date': '05-07-2024', 'nav': '4300.57800'},
          {'date': '04-07-2024', 'nav': '4281.81570'},
          {'date': '03-07-2024', 'nav': '4264.23360'},
          {'date': '02-07-2024', 'nav': '4235.22250'},
          {'date': '01-07-2024', 'nav': '4256.68760'},
          {'date': '28-06-2024', 'nav': '4207.23060'},
          {'date': '27-06-2024', 'nav': '4179.39760'},
          {'date': '26-06-2024', 'nav': '4173.12420'},
          {'date': '25-06-2024', 'nav': '4184.25800'},
          {'date': '24-06-2024', 'nav': '4190.84580'},
          {'date': '21-06-2024', 'nav': '4167.22890'},
          {'date': '20-06-2024', 'nav': '4189.62320'},
          {'date': '19-06-2024', 'nav': '4172.33220'},
          {'date': '18-06-2024', 'nav': '4212.70630'},
          {'date': '14-06-2024', 'nav': '4189.07840'},
          {'date': '13-06-2024', 'nav': '4142.40940'},
          {'date': '12-06-2024', 'nav': '4105.01450'},
          {'date': '11-06-2024', 'nav': '4072.22130'},
          {'date': '10-06-2024', 'nav': '4045.06150'},
          {'date': '07-06-2024', 'nav': '4004.87450'},
          {'date': '06-06-2024', 'nav': '3943.43470'},
          {'date': '05-06-2024', 'nav': '3863.33340'},
          {'date': '04-06-2024', 'nav': '3694.38190'},
          {'date': '03-06-2024', 'nav': '3990.34820'},
          {'date': '31-05-2024', 'nav': '3871.66120'},
          {'date': '30-05-2024', 'nav': '3873.60290'},
          {'date': '29-05-2024', 'nav': '3918.03180'},
          {'date': '28-05-2024', 'nav': '3937.30110'},
          {'date': '27-05-2024', 'nav': '3956.62650'},
          {'date': '24-05-2024', 'nav': '3924.92500'},
          {'date': '23-05-2024', 'nav': '3908.65260'},
          {'date': '22-05-2024', 'nav': '3895.44070'},
          {'date': '21-05-2024', 'nav': '3901.29360'},
          {'date': '17-05-2024', 'nav': '3884.11690'},
          {'date': '16-05-2024', 'nav': '3830.00500'},
          {'date': '15-05-2024', 'nav': '3783.37620'},
          {'date': '14-05-2024', 'nav': '3745.44410'},
          {'date': '13-05-2024', 'nav': '3717.96760'},
          {'date': '10-05-2024', 'nav': '3715.41990'},
          {'date': '09-05-2024', 'nav': '3688.35550'},
          {'date': '08-05-2024', 'nav': '3761.23160'},
          {'date': '07-05-2024', 'nav': '3720.17220'},
          {'date': '06-05-2024', 'nav': '3788.84350'},
          {'date': '03-05-2024', 'nav': '3816.53380'},
          {'date': '02-05-2024', 'nav': '3818.89080'},
          {'date': '30-04-2024', 'nav': '3780.79650'},
          {'date': '29-04-2024', 'nav': '3761.47730'},
          {'date': '26-04-2024', 'nav': '3733.30210'},
          {'date': '25-04-2024', 'nav': '3706.77700'},
          {'date': '24-04-2024', 'nav': '3689.05260'},
          {'date': '23-04-2024', 'nav': '3661.02220'},
          {'date': '22-04-2024', 'nav': '3636.64150'},
          {'date': '19-04-2024', 'nav': '3600.12110'},
          {'date': '18-04-2024', 'nav': '3610.36140'},
          {'date': '16-04-2024', 'nav': '3617.34480'},
          {'date': '15-04-2024', 'nav': '3618.81490'},
          {'date': '12-04-2024', 'nav': '3663.71360'},
          {'date': '10-04-2024', 'nav': '3687.30180'},
          {'date': '09-04-2024', 'nav': '3654.70400'},
          {'date': '08-04-2024', 'nav': '3669.49430'},
          {'date': '05-04-2024', 'nav': '3663.85280'},
          {'date': '04-04-2024', 'nav': '3649.67840'},
          {'date': '03-04-2024', 'nav': '3645.03620'},
          {'date': '02-04-2024', 'nav': '3629.22950'},
          {'date': '01-04-2024', 'nav': '3597.22230'},
          {'date': '31-03-2024', 'nav': '3536.38050'},
          {'date': '28-03-2024', 'nav': '3536.58710'},
          {'date': '27-03-2024', 'nav': '3512.94770'},
          {'date': '26-03-2024', 'nav': '3493.74360'},
          {'date': '22-03-2024', 'nav': '3453.33130'},
          {'date': '21-03-2024', 'nav': '3430.93960'},
          {'date': '20-03-2024', 'nav': '3355.07680'},
          {'date': '19-03-2024', 'nav': '3355.35240'},
          {'date': '18-03-2024', 'nav': '3392.66450'},
          {'date': '15-03-2024', 'nav': '3401.61040'},
          {'date': '14-03-2024', 'nav': '3411.56900'},
          {'date': '13-03-2024', 'nav': '3357.46470'},
          {'date': '12-03-2024', 'nav': '3487.01500'},
          {'date': '11-03-2024', 'nav': '3525.87670'},
          {'date': '07-03-2024', 'nav': '3535.81820'},
          {'date': '06-03-2024', 'nav': '3523.97060'},
          {'date': '05-03-2024', 'nav': '3533.96470'},
          {'date': '04-03-2024', 'nav': '3552.25500'},
          {'date': '01-03-2024', 'nav': '3534.45120'},
          {'date': '29-02-2024', 'nav': '3509.23500'},
          {'date': '28-02-2024', 'nav': '3499.05320'},
          {'date': '27-02-2024', 'nav': '3551.44530'},
          {'date': '26-02-2024', 'nav': '3557.80670'},
          {'date': '23-02-2024', 'nav': '3573.76280'},
          {'date': '22-02-2024', 'nav': '3558.56700'},
          {'date': '21-02-2024', 'nav': '3536.23270'},
          {'date': '20-02-2024', 'nav': '3572.00350'},
          {'date': '19-02-2024', 'nav': '3575.35280'},
          {'date': '16-02-2024', 'nav': '3564.24140'},
          {'date': '15-02-2024', 'nav': '3534.53900'},
          {'date': '14-02-2024', 'nav': '3510.68200'},
          {'date': '13-02-2024', 'nav': '3502.27410'},
          {'date': '12-02-2024', 'nav': '3494.19140'},
          {'date': '09-02-2024', 'nav': '3560.91090'},
          {'date': '08-02-2024', 'nav': '3594.14840'},
          {'date': '07-02-2024', 'nav': '3593.43460'},
          {'date': '06-02-2024', 'nav': '3568.58130'},
          {'date': '05-02-2024', 'nav': '3535.84850'},
          {'date': '02-02-2024', 'nav': '3537.66810'},
          {'date': '01-02-2024', 'nav': '3532.72680'},
          {'date': '31-01-2024', 'nav': '3538.97620'},
          {'date': '30-01-2024', 'nav': '3485.25090'},
          {'date': '29-01-2024', 'nav': '3500.08820'},
          {'date': '25-01-2024', 'nav': '3454.58060'},
          {'date': '24-01-2024', 'nav': '3473.26100'},
          {'date': '23-01-2024', 'nav': '3407.82700'},
          {'date': '19-01-2024', 'nav': '3492.85860'},
          {'date': '18-01-2024', 'nav': '3447.49810'},
          {'date': '17-01-2024', 'nav': '3463.50590'},
          {'date': '16-01-2024', 'nav': '3503.00320'},
          {'date': '15-01-2024', 'nav': '3529.98530'},
          {'date': '12-01-2024', 'nav': '3523.61950'},
          {'date': '11-01-2024', 'nav': '3518.29930'},
          {'date': '10-01-2024', 'nav': '3505.67650'},
          {'date': '09-01-2024', 'nav': '3504.49490'},
          {'date': '08-01-2024', 'nav': '3508.77500'},
          {'date': '05-01-2024', 'nav': '3546.75570'},
          {'date': '04-01-2024', 'nav': '3536.62420'},
          {'date': '03-01-2024', 'nav': '3483.37950'},
          {'date': '02-01-2024', 'nav': '3479.65290'},
          {'date': '01-01-2024', 'nav': '3491.35160'},
          {'date': '29-12-2023', 'nav': '3475.97440'},
          {'date': '28-12-2023', 'nav': '3444.66000'},
          {'date': '27-12-2023', 'nav': '3429.07460'},
          {'date': '26-12-2023', 'nav': '3411.49150'},
          {'date': '22-12-2023', 'nav': '3388.22240'},
          {'date': '21-12-2023', 'nav': '3370.99840'},
          {'date': '20-12-2023', 'nav': '3334.06990'},
          {'date': '19-12-2023', 'nav': '3418.92550'},
          {'date': '18-12-2023', 'nav': '3420.92140'},
          {'date': '15-12-2023', 'nav': '3408.79490'},
          {'date': '14-12-2023', 'nav': '3409.41700'},
          {'date': '13-12-2023', 'nav': '3378.54670'},
          {'date': '12-12-2023', 'nav': '3341.58270'},
          {'date': '11-12-2023', 'nav': '3355.21650'},
          {'date': '08-12-2023', 'nav': '3331.13690'},
          {'date': '07-12-2023', 'nav': '3335.36680'},
          {'date': '06-12-2023', 'nav': '3314.69590'},
          {'date': '05-12-2023', 'nav': '3308.64950'},
          {'date': '04-12-2023', 'nav': '3300.51200'},
          {'date': '01-12-2023', 'nav': '3259.42010'},
          {'date': '30-11-2023', 'nav': '3219.44900'},
          {'date': '29-11-2023', 'nav': '3184.32030'},
          {'date': '28-11-2023', 'nav': '3158.08190'},
          {'date': '24-11-2023', 'nav': '3142.10060'},
          {'date': '23-11-2023', 'nav': '3132.24580'},
          {'date': '22-11-2023', 'nav': '3134.33280'},
          {'date': '21-11-2023', 'nav': '3132.90750'},
          {'date': '20-11-2023', 'nav': '3131.49270'},
          {'date': '17-11-2023', 'nav': '3125.46140'},
          {'date': '16-11-2023', 'nav': '3120.06840'},
          {'date': '15-11-2023', 'nav': '3107.30220'},
          {'date': '13-11-2023', 'nav': '3087.87020'},
          {'date': '10-11-2023', 'nav': '3060.55940'},
          {'date': '09-11-2023', 'nav': '3041.77310'},
          {'date': '08-11-2023', 'nav': '3044.98130'},
          {'date': '07-11-2023', 'nav': '3016.97060'},
          {'date': '06-11-2023', 'nav': '3002.44720'},
          {'date': '03-11-2023', 'nav': '2981.51530'},
          {'date': '02-11-2023', 'nav': '2951.34010'},
          {'date': '01-11-2023', 'nav': '2914.66360'},
          {'date': '31-10-2023', 'nav': '2923.79050'},
          {'date': '30-10-2023', 'nav': '2921.73390'},
          {'date': '27-10-2023', 'nav': '2917.94670'},
          {'date': '26-10-2023', 'nav': '2874.11830'},
          {'date': '25-10-2023', 'nav': '2903.23780'},
          {'date': '23-10-2023', 'nav': '2915.59830'},
          {'date': '20-10-2023', 'nav': '2979.69780'},
          {'date': '19-10-2023', 'nav': '2997.83360'},
          {'date': '18-10-2023', 'nav': '2999.37150'},
          {'date': '17-10-2023', 'nav': '3017.19540'},
          {'date': '16-10-2023', 'nav': '3004.72610'},
          {'date': '13-10-2023', 'nav': '2999.73000'},
          {'date': '12-10-2023', 'nav': '3002.57370'},
          {'date': '11-10-2023', 'nav': '2991.15800'},
          {'date': '10-10-2023', 'nav': '2976.15930'},
          {'date': '09-10-2023', 'nav': '2944.01590'},
          {'date': '06-10-2023', 'nav': '2974.61640'},
          {'date': '05-10-2023', 'nav': '2958.98530'},
          {'date': '04-10-2023', 'nav': '2947.53110'},
          {'date': '03-10-2023', 'nav': '2986.40870'},
          {'date': '29-09-2023', 'nav': '2987.88510'},
          {'date': '27-09-2023', 'nav': '2992.77540'},
          {'date': '26-09-2023', 'nav': '2972.29630'},
          {'date': '25-09-2023', 'nav': '2973.53580'},
          {'date': '22-09-2023', 'nav': '2963.84720'},
          {'date': '21-09-2023', 'nav': '2968.91020'},
          {'date': '20-09-2023', 'nav': '2988.49290'},
          {'date': '18-09-2023', 'nav': '2999.96880'},
          {'date': '15-09-2023', 'nav': '3001.46140'},
          {'date': '14-09-2023', 'nav': '3005.94540'},
          {'date': '13-09-2023', 'nav': '2978.96090'},
          {'date': '12-09-2023', 'nav': '2972.77700'},
          {'date': '11-09-2023', 'nav': '3056.25590'},
          {'date': '08-09-2023', 'nav': '3030.51470'},
          {'date': '07-09-2023', 'nav': '2998.11070'},
          {'date': '06-09-2023', 'nav': '2971.55600'},
          {'date': '05-09-2023', 'nav': '2969.22730'},
          {'date': '04-09-2023', 'nav': '2947.34460'},
          {'date': '01-09-2023', 'nav': '2923.90760'},
          {'date': '31-08-2023', 'nav': '2901.50690'},
          {'date': '30-08-2023', 'nav': '2895.96390'},
          {'date': '29-08-2023', 'nav': '2873.19960'},
          {'date': '28-08-2023', 'nav': '2862.52000'},
          {'date': '25-08-2023', 'nav': '2845.09640'},
          {'date': '24-08-2023', 'nav': '2863.05460'},
          {'date': '23-08-2023', 'nav': '2857.85220'},
          {'date': '22-08-2023', 'nav': '2847.04660'},
          {'date': '21-08-2023', 'nav': '2817.30410'},
          {'date': '18-08-2023', 'nav': '2798.98360'},
          {'date': '17-08-2023', 'nav': '2811.19500'},
          {'date': '16-08-2023', 'nav': '2803.85120'},
          {'date': '14-08-2023', 'nav': '2803.71220'},
          {'date': '11-08-2023', 'nav': '2809.22330'},
          {'date': '10-08-2023', 'nav': '2818.99190'},
          {'date': '09-08-2023', 'nav': '2821.06360'},
          {'date': '08-08-2023', 'nav': '2813.01250'},
          {'date': '07-08-2023', 'nav': '2792.07290'},
          {'date': '04-08-2023', 'nav': '2776.58470'},
          {'date': '03-08-2023', 'nav': '2754.60490'},
          {'date': '02-08-2023', 'nav': '2748.80360'},
          {'date': '01-08-2023', 'nav': '2787.29990'},
          {'date': '31-07-2023', 'nav': '2786.11930'},
          {'date': '28-07-2023', 'nav': '2759.52460'},
          {'date': '27-07-2023', 'nav': '2746.26630'},
          {'date': '26-07-2023', 'nav': '2742.71710'},
          {'date': '25-07-2023', 'nav': '2734.07320'},
          {'date': '24-07-2023', 'nav': '2725.68360'},
          {'date': '21-07-2023', 'nav': '2717.69320'},
          {'date': '20-07-2023', 'nav': '2731.89700'},
          {'date': '19-07-2023', 'nav': '2726.44740'},
          {'date': '18-07-2023', 'nav': '2710.00240'},
          {'date': '17-07-2023', 'nav': '2716.20190'},
          {'date': '14-07-2023', 'nav': '2709.95830'},
          {'date': '13-07-2023', 'nav': '2692.66770'},
          {'date': '12-07-2023', 'nav': '2702.55700'},
          {'date': '11-07-2023', 'nav': '2693.58560'},
          {'date': '10-07-2023', 'nav': '2674.40250'},
          {'date': '07-07-2023', 'nav': '2675.19080'},
          {'date': '06-07-2023', 'nav': '2698.70140'},
          {'date': '05-07-2023', 'nav': '2681.02580'},
          {'date': '04-07-2023', 'nav': '2672.40590'},
          {'date': '03-07-2023', 'nav': '2668.30710'},
          {'date': '30-06-2023', 'nav': '2656.24000'},
          {'date': '28-06-2023', 'nav': '2639.23830'},
          {'date': '27-06-2023', 'nav': '2621.53800'},
          {'date': '26-06-2023', 'nav': '2604.11880'},
          {'date': '23-06-2023', 'nav': '2580.16860'},
          {'date': '22-06-2023', 'nav': '2612.71980'},
          {'date': '21-06-2023', 'nav': '2632.30200'},
          {'date': '20-06-2023', 'nav': '2616.66470'},
          {'date': '19-06-2023', 'nav': '2611.15930'},
          {'date': '16-06-2023', 'nav': '2609.48280'},
          {'date': '15-06-2023', 'nav': '2585.50690'},
          {'date': '14-06-2023', 'nav': '2580.57330'},
          {'date': '13-06-2023', 'nav': '2574.46720'},
          {'date': '12-06-2023', 'nav': '2545.27780'},
          {'date': '09-06-2023', 'nav': '2533.82810'},
          {'date': '08-06-2023', 'nav': '2537.56890'},
          {'date': '07-06-2023', 'nav': '2554.85080'},
          {'date': '06-06-2023', 'nav': '2530.78060'},
          {'date': '05-06-2023', 'nav': '2528.14980'},
          {'date': '02-06-2023', 'nav': '2515.46850'},
          {'date': '01-06-2023', 'nav': '2501.28740'},
          {'date': '31-05-2023', 'nav': '2493.97360'},
          {'date': '30-05-2023', 'nav': '2488.78590'},
          {'date': '29-05-2023', 'nav': '2484.09240'},
          {'date': '26-05-2023', 'nav': '2471.92110'},
          {'date': '25-05-2023', 'nav': '2452.14820'},
          {'date': '24-05-2023', 'nav': '2442.09060'},
          {'date': '23-05-2023', 'nav': '2433.60890'},
          {'date': '22-05-2023', 'nav': '2429.91890'},
          {'date': '19-05-2023', 'nav': '2421.31920'},
          {'date': '18-05-2023', 'nav': '2420.65990'},
          {'date': '17-05-2023', 'nav': '2426.26500'},
          {'date': '16-05-2023', 'nav': '2432.66100'},

In [68]:
##### Display the data as a DataFrame
df3 = pd.DataFrame(list(data3.items()))

df3.head(10)

                   0                                                  1
0         fund_house                           Nippon India Mutual Fund
1        scheme_type                                 Open Ended Schemes
2    scheme_category                       Equity Scheme - Mid Cap Fund
3        scheme_code                                             118668
4        scheme_name  Nippon India Growth Fund - Direct Plan Growth ...
5  scheme_start_date         {'date': '02-01-2013', 'nav': '507.16170'}
6               data  [{'date': '04-11-2024', 'nav': '4371.51340'}, ...

##### Can manipulate the data based on our need

In [69]:
##### List the Historical NAV Data
Hist_NAV = data3 ['data']

#### Display this data as DataFrame
df_Hist_NAV = pd.DataFrame(Hist_NAV, columns=["date", "nav"])

df_Hist_NAV.head()

         date         nav
0  04-11-2024  4371.51340
1  31-10-2024  4388.91090
2  30-10-2024  4389.50920
3  29-10-2024  4393.86540
4  28-10-2024  4354.28520

In [52]:
# pprint.pprint(Hist_NAV)

In [71]:
##### Save the DataFrame to a CSV file
file_path = "/content/HistNAV_118668.csv"                                       # Update the file path to a location accessible in Colab

df_Hist_NAV.to_csv(file_path, index=False)                                      # Save the DataFrame as a CSV file

print(f"Historical NAV data for the scheme code-{Scheme_Code} saved to: {file_path}")

Historical NAV data for the scheme code-118668 saved to: /content/HistNAV_118668.csv

In [72]:
##### Downlaod the file for Google Colab

from google.colab import files
files.download(file_path)